'use client';
import * as React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { Container, Typography, AppBar, Toolbar, Button, Box } from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme.js';

function Home() {
  return (
      <React.StrictMode>
      <ThemeProvider theme={theme}>
        <Head>
          <title> Pantry Raid Co. - Pantry Tracker</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="favicon.ico" />
        </Head>

        <Box
          sx = {{
            display: 'flex',
            backgroundImage: `url('/background.jpg')`, 
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            height: '100vh',
            width: '100vw',
            position: 'fixed',
            zIndex: -1,
          }}
        />
        <AppBar position="fixed" color="secondary">
          <Toolbar>
            <img src="cart.png" alt="PantryRaid Co. Logo" key="logo" style={{ marginRight: 10, height: 30 }} />
            <Typography variant="h6" component="div" color="white" fontFamily="Bubblegum Sans" fontSize='3' sx={{ flexGrow: 1 }}>
              PantryRaid Co.
            </Typography>
            <Link href="/login">
              <Button 
                variant="contained"  
                color="primary" 
                sx={{ ml: 2, color: 'white' }}>
                Login
              </Button>
            </Link>
          </Toolbar>
        </AppBar>

        <main>
          <Container maxWidth='md'>
            <Box
              sx={{
                display: 'flex',
                flexDirection: 'column',
                justifyContent: 'center',
                alignItems: 'center',
                textAlign: 'center',
                height: '100vh',
              }}
            >
              <Typography variant="h2" color='primary' component="h1" mb={2} fontFamily='Pacifico' sx={{ textDecoration: 'underline' }}>
                Welcome to PantryRaid Co.
              </Typography>
              <Typography variant="body1" color='primary' fontSize="1.2rem" gutterBottom sx={{ paddingLeft: 10, paddingRight: 10 }}>
                Our Pantry Tracker helps you effortlessly manage your pantry, reduce food waste, and discover recipes tailored to what you already have. 
                Try PantryRaid Co. today and make your kitchen smarter and more efficient!
              </Typography>
              <Box display="flex" justifyContent="center" alignItems="center" mt={2}>
                <Link href="/signup">
                <Button variant="contained" 
                  sx={{ padding: '8px 20px', 
                        fontSize: '2.5rem', 
                        color: '#ffffff',
                        fontFamily: 'Bubblegum Sans', 
                  }}
                >
                  Try Now
                </Button>
                </Link>
              </Box>
            </Box>
          </Container>
        </main>
      </ThemeProvider>
      </React.StrictMode>
  );
}

export default Home