"use client";
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Head from 'next/head';
import { Container, Typography, AppBar, Toolbar, Button, Box, TextField } from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import theme from './theme.js'; // Ensure this is the same theme file
import Link from 'next/link';
import { signInWithEmailAndPassword } from 'firebase/auth';
import { auth } from '../firebase/firebase.js'; // Import from your firebaseConfig

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const router = useRouter();

  const handleSubmit = async (event) => {
    event.preventDefault();
    setLoading(true);
    setError(null);

    try {
        const userCredential = await signInWithEmailAndPassword(auth, email, password);
        console.log('Login successful:', userCredential);
        router.push('/inventory'); // Redirect after successful login
    } catch (error) {
        console.error('Login error:', error);
        alert(error.message); // Show an alert with the error message
    } finally {
        setLoading(false);
    }
};

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Pantry Raid Co - Pantry Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar position="fixed" color="secondary">
        <Toolbar>
          <img src="cart.png" alt="PantryRaid Co Logo" key="logo" style={{ marginRight: 10, height: 30 }} />
          <Link href="/">
              <Typography variant="h6" component="div" color="white" fontFamily="Bubblegum Sans" fontSize="3" sx={{ flexGrow: 1 }}>
              PantryRaid Co
              </Typography>
          </Link>
          <Box sx={{ flexGrow: 1 }} />
          <Link href="/signup">
            <Button variant="contained" color="primary" sx={{ ml: 2, color: 'white' }}>
              Register
            </Button>
          </Link>
        </Toolbar>
      </AppBar>

      <Box
        sx={{
          display: 'flex',
          backgroundImage: 'url(/background.jpg)',
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          height: '100vh',
          width: '100vw',
          position: 'fixed',
          zIndex: -1,
        }}
      />

      <main>
        <Container maxWidth="md">
          <Box
            sx={{
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
              textAlign: 'center',
              height: '100vh',
            }}
          >
            <Box
              sx={{
                width: '80%',
                height: '50%',
                margin: '50px 0 0 0',
                backgroundColor: '#dd885090',
              }}
            >
              <Typography
                variant="h2"
                color="primary"
                component="h1"
                mb={2}
                fontFamily="Pacifico"
                sx={{
                  textDecoration: 'underline',
                  marginTop: 4,
                }}
              >
                Login
              </Typography>
              <form onSubmit={handleSubmit}>
                <TextField
                  id="email"
                  label="Email"
                  variant="outlined"
                  margin="normal"
                  required
                  fullWidth
                  sx={{ padding: '0 90px' }}
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  aria-label="Email"
                  InputLabelProps={{
                    sx: {
                        padding: '0 90px',
                    },
                }}
                />
                <TextField
                  type="password"
                  label="Password"
                  variant="outlined"
                  margin="normal"
                  required
                  fullWidth
                  sx={{ padding: '0 90px' }}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  aria-label="Password"
                  InputLabelProps={{
                    sx: {
                        padding: '0 90px',
                    },
                }}
                />
                <Button
                  variant="contained"
                  color="primary"
                  type="submit"
                  disabled={loading}
                  sx={{ fontSize: '1.5rem', padding: '5px 20px', mt: 4, color: 'white' }}
                >
                  {loading ? 'Logging In...' : 'Login'}
                </Button>
              </form>
            </Box>
          </Box>
        </Container>
      </main>
    </ThemeProvider>
  );
}
